# -*- coding: utf-8 -*-
"""МеженинА_02.05.2023_Практикум.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vQsWox67uaW-l98fWwO1Col2AYU1l_kr
"""

with open("Уэллс_-_Война_миров.txt", "r") as file:
  text = file.read()

import re
text = text.replace('\xa0', ' ')
text = text.replace('\n', ' ')
text = re.sub(r'[^\w\s]', '', text)
text = re.sub(r'\d+', '', text)

from collections import Counter
words = text.lower().split(' ')
word_counts = Counter(words)

word_counts.pop('')

top_words = dict(word_counts.most_common(20))

import matplotlib.pyplot as plt
plt.bar(top_words.keys(), top_words.values())
plt.xticks(rotation=45)
plt.show()

num_chars = len(text)
num_chars_no_spaces = len(text.replace(' ', ''))
num_lines = text.count('\n') + 1
num_words = sum(word_counts.values())

print(f"Количество строк: {num_lines}")
print(f"Количество слов: {num_words}")

print(f"Количество символов (с учётом пробелов): {num_chars}")
print(f"Количество символов (без учёта пробелов): {num_chars_no_spaces}")